language: rust
sudo: false

os:
  - osx
  - linux

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

apt:
    packages:
    - git
    - gcc
    - g++
    - glib-2.0
    - make
    - cmake
    - pkg-config
    - software-properties-common
    - wget
    - swig
    - flex
    - bison
    - python-all-dev
    - python-gobject-dev

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; brew install radare2; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; git clone https://github.com/radare/radare2.git; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; cd radare2; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; ./sys/install.sh; fi
