language: rust
sudo: required # for building radare

os:
  - osx
  - linux

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

apt:
    packages:
    - git
    - clang
    - gcc
    - g++
    - glib-2.0
    - make
    - cmake
    - pkg-config
    - software-properties-common
    - wget
    - swig
    - flex
    - bison
    - python-all-dev
    - python-gobject-dev

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install radare2 clang; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then git clone https://github.com/radare/radare2.git; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd radare2; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./sys/install.sh; fi
